### ISSUE TITLE
Do not put '_' in your sample names

### ISSUE THREAD

**Issue by farshadniazi** [biocore/emperor#351]
When run make_emperor.py if you have '_' character in any sample name, the name would be truncated from that character  to the end of sample name and you would get """make_emperor.py: error: The metadata mapping file has fewer sample identifiers than the coordinates file. Verify you are using a mapping file that contains at least all the samples contained in the coordinates file(s). You can force the script to ignore these samples by passing the '--ignore_missing_samples' flag."""

Example:
--Sample names from my MAP file:

---------------------------------------------------------

15N_S12	
20N_S60	
31DN_S36
31N_S24	
15T_S95
15TM1_S23
31T_S48
BkM1_S11
BkM2_S35
R1_S72
R2_S84
X96
----------------------------------------------------------

  and sample names in my weighted_unifrac_pc.txt file:

---------------------------------------------------------
R1
31DN
R2
31N
15N
20N
X96
BkM1
15T
31T
BkM2
15TM1

**Comment by ElDeveloper** [comment]
Hello, note that emperor does not generate the coordinates matrix i.e.
the contents of weighted_unifrac_pc.txt, this is generated (usually) by
principal_coordinates.py in QIIME. The problem you are experiencing
arises because '_' is an invalid character for sample names. See this
document:
http://qiime.org/documentation/file_formats.html#mapping-file-overview

Emperor is actually giving a correct error as the sample names don't
match between the coordinates matrix and the mapping file. I would
recommend one of two things:

1.- Re-do your analysis to remove the underscores form the very
beginning (before demuxing).
2.- Change your mapping file so sample names match with the coordinates
matrix.

I'll close this issue for now, but please let us know if you find a
problem when generating the plot!

**Comment by farshadniazi** [comment]
You are right on all your points. Thanks a lot.
