### ISSUE TITLE
The index.html file name is not very descriptive.

### ISSUE THREAD

**Issue by jwdebelius** [biocore/emperor#365]
The utility, as I understand, of index.html is the ability to drag and drop folders into the browser. I would estimate less than 1/4 of Emperor's user community is aware of this feature.

I'd suggest creating redundancy in the way emperor names the files, either passing the metric or a custom filename.

**Comment by ElDeveloper** [comment]
A solution for this would be to add an `--index_filename` or `--html_filename` to the command line interface, the default value would be `index.html`.

However I don't like this solution at all because users could easily get to a point where they end up with `index.html` + `emperor_required_resources` that do not match between each other.

**Comment by ElDeveloper** [comment]
This is no longer an issue in the new API:

- Files created from the Python API are named by the user (so this issue is solved).
- Artifacts in QIIME2 hide the HTML file and dependencies.
