### ISSUE TITLE
Empty plots when using euclidean distance (unifrac, bray curtis ok)

### ISSUE THREAD

**Issue by lfaller** [biocore/emperor#426]
Hi all,

I ran emperor through the qiime script "beta_diversity_through_plots.py" to generate PCoA plots for a dataset. I tried using weighted/unweighted unifrac and bray-curtis distance measures, and the plots came out fine. However, using euclidean distance, the plot is empty (no dots for the samples, just the labels "PC1", "PC2", and "PC3" together with variance explained). The "parallel" view does show data.

The script didn't report any errors in the log output, and the files "euclidean_pc.txt" and "euclidean_dm.txt" contain valid-looking data.

Thanks in advance for any advice!

Best,
~Lina

![screen shot 2015-10-07 at 9 46 17 am](https://cloud.githubusercontent.com/assets/7854149/10339251/5d1c8106-6cd8-11e5-8f0d-0b005d71bbe1.png)
![screen shot 2015-10-07 at 9 46 29 am](https://cloud.githubusercontent.com/assets/7854149/10339250/5d1b8300-6cd8-11e5-9efb-2056209cd8a6.png)

**Comment by ElDeveloper** [comment]
Hello @lfaller, it seems like you are using verison 0.9.3 of EMPeror, this was a bug that we fixed in #233 (originally reported in #220) and shipped as part of [0.9.4](https://github.com/biocore/emperor/blob/master/ChangeLog.md#emperor-094-10-sept-2014). The solution would be to update the version of emperor that you are using - let us know if you have issues with this.

**Comment by lfaller** [comment]
Great, thanks for the tip!
