### ISSUE TITLE
custom_axes parameter results in less informative axis labels

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/emperor#562]
In `1.0.0beta5`, using *custom axes* causes the PC axes in the plot to be named `0`, `1,`, ..., and in the *Axis* tab, the percent variations are associated with the wrong axes. 

From [the QIIME 2 moving pictures tutorial emperor plot](https://view.qiime2.org/?src=https%3A%2F%2Fdocs.qiime2.org%2F2017.2%2Fdata%2Ftutorials%2Fmoving-pictures%2Fcm1441%2Funweighted-unifrac-emperor.qzv):

<img width="1073" alt="screenshot 2017-03-08 15 03 56" src="https://cloud.githubusercontent.com/assets/192372/23726159/7b233dfe-0410-11e7-8c65-cab59173237e.png">

**Comment by ElDeveloper** [comment]
@gregcaporaso, there are two problems here, the first one is that the axis are being labeled `0, 1, 2 ... N`, then the second one is that the scree plot displays incorrect data.

For the first problem, this is not specific to custom axes, it will happen with **any** ordination object that has been serialized, because scikit-bio will not store the ordination name, nor the short name for the ordination (both attributes that exist already as part of the `OrdinationResults` class). So the solution for this issue is one of the following:

1) Fix the file-format in scikit-bio to include this data (https://github.com/biocore/scikit-bio/issues/665).

2) Add a special case to Emperor to *patch* and fix the 0, 1, ... to a generic name like `Ax 1`, or something like that.

3) Do both 1 and 2.

4) Change the parser in scikit-bio to infer what ordination type is being read based upon the present attributes. 

My preference is to do option 1, but any input is appreciated.

As for the second problem (the scree plot and the incorrect labels), this is a problem that needs to be fixed in Emperor.

**Comment by antgonza** [comment]
For 1, should this be part of the Q2 artifact or skbio?

**Comment by ElDeveloper** [comment]
I suspect that if it is fixed in the skbio IO module, this will
percolate to the Q2 representation. But I am not 100% sure about that.

**Comment by ElDeveloper** [comment]
After looking at the scikit-bio code, another problem is that when the `OrdinationResults` object is loaded in memory, it uses a pandas DataFrame and has appropriate labels for the axes i.e. a PCoA object will have the columns labeled as PC1, PC2, ... PCN, however when this data is serialized the column names are completely lost. So when they are de-serialized the column names are set as the default for Pandas which is 0, 1, 2 ... N (as seen in @gregcaporaso's bug report).

**Comment by gregcaporaso** [comment]
@ElDeveloper, I think calling them `Axis 1`, `Axis 2`, ... (1-indexed, not 0-indexed) would be a good way to deal with this in Emperor, but it could also be addressed in skbio (so options 1 and 2). I'd vote for doing both, as option 2 is a short-term fix so would get into the next emperor release and to users without having to wait for an skbio release.

**Comment by ElDeveloper** [comment]
@gregcaporaso, yes after looking over at the skbio code-base this seems more complicated, it would basically require a different version of the ordination results format so that we can actually get this right. For now, the fix will be temporary and only in Emperor. I will assume that if the column names are `0 ... N`, then that means that those are produced by the scikit-bio bug and that they can be safely replaced by `Ax 1 ... Ax N`.
