### ISSUE TITLE
change the font size on axes

### ISSUE THREAD

**Issue by antgonza** [biocore/emperor#598]
came up in a workshop

**Comment by ElDeveloper** [comment]
Is this issue about controlling the size of the axes labels with a slider or about changing the default value? The slider seems like overkill to me.

**Comment by antgonza** [comment]
I can't remember if we went to those details, how to control. I guess as long as we can control ... what about predefined sizes: regular, large, small?

**Comment by ElDeveloper** [comment]
My gut feeling is that an additional "size" controller might be overkill 
and that perhaps the reason why this was requested was because we need a 
better default size? I recall the perceived text size changed a bit when 
we moved from a perspective to an orthographic camera. So I was thinking 
maybe we can just make the font a little bigger?

**Comment by antgonza** [comment]
Let's start with that ... and see if we hear back again ...
