### ISSUE TITLE
cubes always face the camara

### ISSUE THREAD

**Issue by antgonza** [biocore/emperor#601]
which makes them look like squares ...

**Comment by ebolyen** [comment]
This probably isn't super helpful, but I noticed that you can see other angles when you toggle autorotation on, toggle it off, and the recenter the camera. (In case that is of any diagnostic use.)

**Comment by ElDeveloper** [comment]
This is by design, to ensure the shapes do not appear ambiguous when the view is rotated. The original concern being that, for example, from above a cone might look like a sphere-like object and this in turn could be misleading confusing the cone- and the sphere-shaped groups. Other situations like this might be possible for other shapes.

I've been thinking that we might want to change the shapes to no longer be 3-dimensional geometries. We might be OK with making them 2D objects. Spheres would become circles, cubes would become squares, etc. In other words, would you prefer A or B:

# A (three-dimensional objects)
<img width="1375" alt="screen shot 2017-10-30 at 4 49 31 pm" src="https://user-images.githubusercontent.com/375307/32195041-86e35b2e-bd92-11e7-9dae-faec3505c3de.png">

# B (two-dimensional objects)
<img width="1376" alt="screen shot 2017-10-30 at 4 49 39 pm" src="https://user-images.githubusercontent.com/375307/32195056-93db7f5a-bd92-11e7-8ad4-b6786514ba15.png">

This would also address the problem in #544 (samples changing color due to the light reflection on the material) and #604 (using 2D glyphs in 2D-mode).

**Comment by rob-knight** [comment]
A looks a lot nicer than B…remember this was the original motivation for using KiNG rather than matplotlib or god forbid excel...

On Oct 30, 2017, at 1:55 PM, Yoshiki Vázquez Baeza <notifications@github.com<mailto:notifications@github.com>> wrote:


This is by design, to ensure the shapes do not appear ambiguous when the view is rotated. The original concern being that, for example, from above a cone might look like a sphere-like object and this in turn could be misleading confusing the cone- and the sphere-shaped groups. Other situations like this might be possible for other shapes.

I've been thinking that we might want to change the shapes to no longer be 3-dimensional geometries. We might be OK with making them 2D objects. Spheres would become circles, cubes would become squares, etc. In other words, would you prefer A or B:

A (three-dimensional objects)

[screen shot 2017-10-30 at 4 49 31 pm]<https://user-images.githubusercontent.com/375307/32195041-86e35b2e-bd92-11e7-9dae-faec3505c3de.png>

B (two-dimensional objects)

[screen shot 2017-10-30 at 4 49 39 pm]<https://user-images.githubusercontent.com/375307/32195056-93db7f5a-bd92-11e7-8ad4-b6786514ba15.png>

This would also address the problem in #544<https://github.com/biocore/emperor/issues/544> (samples changing color due to the light reflection on the material) and #604<https://github.com/biocore/emperor/issues/604> (using 2D glyphs in 2D-mode).

**Comment by antgonza** [comment]
Agree with @rob-knight is this something that can happen on the fly? Basically, have a checkbox that allows you to change the "point" from 2D to 3D so if we encounter these artifacts the solution is to make then 2D at any given angle.

**Comment by ElDeveloper** [comment]
Noted. Yes, we can make it such that there's additional geometries 
available i.e. circles, squares, triangles, etc.
